[versions]
coroutines = "1.6.4"
kotlin = "2.1.10"
kotlinTelegramBot = "6.3.0"
ktor = "3.1.0"
serialization = "1.4.1"
serializationPlugin = "1.7.21"

[libraries]
kotlin-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "coroutines" }
kotlin-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "serialization" }
kotlin-telegram-bot = { group = "io.github.kotlin-telegram-bot.kotlin-telegram-bot", name = "telegram", version.ref = "kotlinTelegramBot" }
ktor-client-cio = { group = "io.ktor", name = "ktor-client-cio", version.ref = "ktor" }
ktor-client-core = { group = "io.ktor", name = "ktor-client-core", version.ref = "ktor" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serializationPlugin" }
